--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website text,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    -- AIBS-specific lead/pipeline fields
    pipeline_status       text,
    origine_lead          text,
    formation_souhaitee   text,
    formation_slug        text,
    utm_source            text,
    utm_medium            text,
    utm_campaign          text,
    calendly_reserved     boolean not null default false,
    qualification_bot     boolean not null default false,
    reponse_relance_email boolean not null default false,
    reponse_relance_wa    boolean not null default false,
    indice_no_show        integer not null default 0,
    lien_calendly         text,
    valeur_estimee        numeric(10,2),
    converted_at          timestamp with time zone,
    airtable_id           text unique,
    meta_lead_id          text,
    updated_at            timestamp with time zone default now()
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    -- AIBS-specific pipeline fields
    formation_souhaitee text,
    airtable_lead_id    text
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email text not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

-- ===========================================================================
-- AIBS – Tables métier École d'Art
-- ===========================================================================

create table public.formations (
    id                  bigint generated by default as identity primary key,
    created_at          timestamp with time zone not null default now(),
    airtable_id         text unique,
    nom                 text not null,
    slug                text unique,
    sous_titre          text,
    description         text,
    domaine_artistique  text,
    duree_jours         numeric,
    duree_texte         text,
    lieu_principal      text,
    prix_catalogue      numeric(10,2),
    tarif               text,
    statut              text,
    date_texte          text,
    objectifs           text,
    intervenants_texte  text,
    format              text,
    points_forts        text,
    accroche            text,
    livrables           text,
    flexibilite         text,
    programme_json      jsonb,
    ordre               integer,
    image               jsonb
);

create index formations_slug_idx   on public.formations(slug);
create index formations_statut_idx on public.formations(statut);

create table public.intervenants (
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone not null default now(),
    airtable_id  text unique,
    first_name   text not null,
    last_name    text not null,
    email        text,
    phone        text,
    biographie   text,
    specialites  text[],
    statut       text,
    date_ajout   date,
    notes        text,
    hide_badge   boolean not null default false,
    avatar       jsonb
);

create table public.training_sessions (
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone not null default now(),
    airtable_id  text unique,
    session_name text not null,
    formation_id bigint references public.formations(id) on delete set null,
    start_date   date,
    end_date     date,
    location     text,
    capacity     integer,
    status       text,
    notes        text
);

create index training_sessions_formation_id_idx on public.training_sessions(formation_id);
create index training_sessions_start_date_idx   on public.training_sessions(start_date);

create table public.formation_intervenants (
    formation_id    bigint not null references public.formations(id)    on delete cascade,
    intervenant_id  bigint not null references public.intervenants(id)  on delete cascade,
    primary key (formation_id, intervenant_id)
);

create table public.session_intervenants (
    session_id      bigint not null references public.training_sessions(id) on delete cascade,
    intervenant_id  bigint not null references public.intervenants(id)      on delete cascade,
    primary key (session_id, intervenant_id)
);

create table public.inscriptions (
    id                   bigint generated by default as identity primary key,
    created_at           timestamp with time zone not null default now(),
    airtable_id          text unique,
    numero_inscription   text,
    date_inscription     date,
    contact_id           bigint references public.contacts(id)          on delete set null,
    session_id           bigint references public.training_sessions(id) on delete set null,
    statut               text,
    mode_financement     text,
    montant_total        numeric(10,2),
    commentaires         text,
    date_validation      date,
    created_by           text
);

create index inscriptions_contact_id_idx on public.inscriptions(contact_id);
create index inscriptions_session_id_idx on public.inscriptions(session_id);
create index inscriptions_statut_idx     on public.inscriptions(statut);

create table public.paiements (
    id                  bigint generated by default as identity primary key,
    created_at          timestamp with time zone not null default now(),
    airtable_id         text unique,
    numero_paiement     text,
    date_paiement       date,
    montant             numeric(10,2),
    statut_paiement     text,
    mode_paiement       text,
    type_financement    text,
    commentaire         text,
    inscription_id      bigint references public.inscriptions(id) on delete set null,
    contact_id          bigint references public.contacts(id)     on delete set null
);

create index paiements_inscription_id_idx on public.paiements(inscription_id);
create index paiements_contact_id_idx     on public.paiements(contact_id);

create table public.interactions (
    id               bigint generated by default as identity primary key,
    created_at       timestamp with time zone not null default now(),
    airtable_id      text unique,
    titre            text,
    date_heure       timestamp with time zone,
    type_interaction text,
    message          text,
    canal            text,
    statut_suivi     text,
    responsable      text,
    contact_id       bigint references public.contacts(id) on delete set null
);

create index interactions_contact_id_idx on public.interactions(contact_id);

create table public.newsletter_subscribers (
    id                   bigint generated by default as identity primary key,
    created_at           timestamp with time zone not null default now(),
    airtable_id          text unique,
    email                text not null unique,
    prenom               text,
    date_inscription     date,
    source               text,
    statut               text,
    date_desabonnement   date,
    langue               text
);

create table public.documents (
    id              bigint generated by default as identity primary key,
    created_at      timestamp with time zone not null default now(),
    updated_at      timestamp with time zone default now(),
    contact_id      bigint references public.contacts(id) on delete set null,
    title           text not null,
    type_document   text not null default 'autre',
    file_url        text,
    file_name       text,
    statut          text not null default 'en-attente',
    notes           text,
    sales_id        bigint references public.sales(id)
);

create index documents_contact_id_idx     on public.documents(contact_id);
create index documents_type_document_idx  on public.documents(type_document);
create index documents_statut_idx         on public.documents(statut);
