-- =============================================================================
-- Email Campaigns & Logs — envoi direct et campagnes via Resend / artaibs.fr
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Campagnes email
-- ---------------------------------------------------------------------------
create table if not exists public.email_campaigns (
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone not null default now(),
    name        text not null,
    subject     text not null,
    html_body   text not null,
    status      text not null default 'draft',   -- draft | sending | sent | failed
    sent_at     timestamp with time zone,
    sales_id    integer references public.sales(id),
    total_sent  integer not null default 0,
    total_error integer not null default 0
);

-- ---------------------------------------------------------------------------
-- 2. Contacts d'une campagne (destinataires)
-- ---------------------------------------------------------------------------
create table if not exists public.email_campaign_contacts (
    id          bigint generated by default as identity primary key,
    campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
    contact_id  integer references public.contacts(id) on delete cascade,
    email       text not null,
    first_name  text,
    status      text not null default 'pending',  -- pending | sent | failed
    sent_at     timestamp with time zone,
    error_msg   text
);

create index if not exists email_campaign_contacts_campaign_idx
    on public.email_campaign_contacts(campaign_id);

-- ---------------------------------------------------------------------------
-- 3. Log de tous les emails envoyés (direct + campagne)
-- ---------------------------------------------------------------------------
create table if not exists public.email_logs (
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone not null default now(),
    to_email    text not null,
    subject     text not null,
    contact_id  integer references public.contacts(id) on delete set null,
    campaign_id bigint references public.email_campaigns(id) on delete set null,
    status      text not null default 'sent',     -- sent | failed
    error_msg   text,
    resend_id   text,    -- message ID returned by Resend
    sales_id    integer references public.sales(id)
);

create index if not exists email_logs_contact_idx  on public.email_logs(contact_id);
create index if not exists email_logs_campaign_idx on public.email_logs(campaign_id);
create index if not exists email_logs_created_idx  on public.email_logs(created_at desc);

-- ---------------------------------------------------------------------------
-- 4. RLS – seuls les sales connectés peuvent lire/écrire
-- ---------------------------------------------------------------------------
alter table public.email_campaigns         enable row level security;
alter table public.email_campaign_contacts enable row level security;
alter table public.email_logs              enable row level security;

create policy "sales can manage email_campaigns"
    on public.email_campaigns for all
    using (auth.uid() is not null)
    with check (auth.uid() is not null);

create policy "sales can manage email_campaign_contacts"
    on public.email_campaign_contacts for all
    using (auth.uid() is not null)
    with check (auth.uid() is not null);

create policy "sales can manage email_logs"
    on public.email_logs for all
    using (auth.uid() is not null)
    with check (auth.uid() is not null);
