-- =============================================================================
-- AIBS – Extension du schéma CRM pour Art International Business School
-- Migre toutes les tables Airtable : Formations, Sessions, Intervenants,
-- Inscriptions, Paiements, Interactions, Newsletter
-- + Étend contacts et deals avec les champs AIBS spécifiques
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Extension de la table contacts (champs pipeline leads AIBS)
-- ---------------------------------------------------------------------------
alter table public.contacts
    add column if not exists pipeline_status      text,          -- Statut pipeline lead (Nouveau, Qualifié, Inscrit…)
    add column if not exists origine_lead         text,          -- Source (Meta Lead Ads, Organique, etc.)
    add column if not exists formation_souhaitee  text,          -- Formation demandée (texte libre + id slug)
    add column if not exists formation_slug       text,          -- Slug de la formation (doublage-voix, court-metrage…)
    add column if not exists utm_source           text,
    add column if not exists utm_medium           text,
    add column if not exists utm_campaign         text,
    add column if not exists calendly_reserved    boolean        not null default false,
    add column if not exists qualification_bot    boolean        not null default false,
    add column if not exists reponse_relance_email boolean       not null default false,
    add column if not exists reponse_relance_wa   boolean        not null default false,
    add column if not exists indice_no_show       integer        not null default 0,
    add column if not exists lien_calendly        text,
    add column if not exists valeur_estimee       numeric(10,2),
    add column if not exists converted_at         timestamp with time zone,
    add column if not exists airtable_id          text           unique;  -- dédup migration

-- Index pour recherche rapide sur le pipeline
create index if not exists contacts_pipeline_status_idx on public.contacts(pipeline_status);
create index if not exists contacts_airtable_id_idx     on public.contacts(airtable_id);

-- ---------------------------------------------------------------------------
-- 2. Extension de la table deals (lien formation / inscription AIBS)
-- ---------------------------------------------------------------------------
alter table public.deals
    add column if not exists formation_souhaitee text,
    add column if not exists airtable_lead_id    text;          -- ref Airtable Lead ID pendant la migration

-- ---------------------------------------------------------------------------
-- 3. Formations – catalogue des programmes de formation
-- ---------------------------------------------------------------------------
create table if not exists public.formations (
    id                  bigint generated by default as identity primary key,
    created_at          timestamp with time zone not null default now(),
    airtable_id         text unique,
    nom                 text not null,
    slug                text unique,
    sous_titre          text,
    description         text,
    domaine_artistique  text,
    duree_jours         numeric,
    duree_texte         text,
    lieu_principal      text,
    prix_catalogue      numeric(10,2),
    tarif               text,
    statut              text,
    date_texte          text,
    objectifs           text,
    intervenants_texte  text,
    format              text,
    points_forts        text,
    accroche            text,
    livrables           text,
    flexibilite         text,
    programme_json      jsonb,
    ordre               integer
);

create index if not exists formations_slug_idx   on public.formations(slug);
create index if not exists formations_statut_idx on public.formations(statut);

-- ---------------------------------------------------------------------------
-- 4. Intervenants – formateurs / artistes intervenants
-- ---------------------------------------------------------------------------
create table if not exists public.intervenants (
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone not null default now(),
    airtable_id  text unique,
    first_name   text not null,
    last_name    text not null,
    email        text,
    phone        text,
    biographie   text,
    specialites  text[],
    statut       text,               -- Interne / Externe
    date_ajout   date,
    notes        text,
    hide_badge   boolean not null default false
);

-- ---------------------------------------------------------------------------
-- 5. Training Sessions – sessions planifiées d'une formation
-- ---------------------------------------------------------------------------
create table if not exists public.training_sessions (
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone not null default now(),
    airtable_id  text unique,
    session_name text not null,
    formation_id bigint references public.formations(id) on delete set null,
    start_date   date,
    end_date     date,
    location     text,
    capacity     integer,
    status       text,               -- Planned / Ongoing / Completed / Cancelled
    notes        text
);

create index if not exists training_sessions_formation_id_idx on public.training_sessions(formation_id);
create index if not exists training_sessions_start_date_idx   on public.training_sessions(start_date);

-- ---------------------------------------------------------------------------
-- 6. Tables de jonction many-to-many
-- ---------------------------------------------------------------------------
create table if not exists public.formation_intervenants (
    formation_id    bigint not null references public.formations(id)    on delete cascade,
    intervenant_id  bigint not null references public.intervenants(id)  on delete cascade,
    primary key (formation_id, intervenant_id)
);

create table if not exists public.session_intervenants (
    session_id      bigint not null references public.training_sessions(id) on delete cascade,
    intervenant_id  bigint not null references public.intervenants(id)      on delete cascade,
    primary key (session_id, intervenant_id)
);

-- ---------------------------------------------------------------------------
-- 7. Inscriptions – dossiers d'inscription d'un contact à une session
-- ---------------------------------------------------------------------------
create table if not exists public.inscriptions (
    id                   bigint generated by default as identity primary key,
    created_at           timestamp with time zone not null default now(),
    airtable_id          text unique,
    numero_inscription   text,
    date_inscription     date,
    contact_id           bigint references public.contacts(id)          on delete set null,
    session_id           bigint references public.training_sessions(id) on delete set null,
    statut               text,               -- En attente, Validé, Annulé, Remboursé…
    mode_financement     text,               -- AFDAS, France Travail, Autofinancement, Autre
    montant_total        numeric(10,2),
    commentaires         text,
    date_validation      date,
    created_by           text
);

create index if not exists inscriptions_contact_id_idx on public.inscriptions(contact_id);
create index if not exists inscriptions_session_id_idx on public.inscriptions(session_id);
create index if not exists inscriptions_statut_idx     on public.inscriptions(statut);

-- ---------------------------------------------------------------------------
-- 8. Paiements – suivi des paiements liés aux inscriptions
-- ---------------------------------------------------------------------------
create table if not exists public.paiements (
    id                  bigint generated by default as identity primary key,
    created_at          timestamp with time zone not null default now(),
    airtable_id         text unique,
    numero_paiement     text,
    date_paiement       date,
    montant             numeric(10,2),
    statut_paiement     text,               -- En attente, Reçu, Partiel, Remboursé
    mode_paiement       text,               -- Virement, Chèque, Carte, Espèces, Autre
    type_financement    text,               -- AFDAS, France Travail, Autofinancement, Autre
    commentaire         text,
    inscription_id      bigint references public.inscriptions(id) on delete set null,
    contact_id          bigint references public.contacts(id)     on delete set null
);

create index if not exists paiements_inscription_id_idx on public.paiements(inscription_id);
create index if not exists paiements_contact_id_idx     on public.paiements(contact_id);

-- ---------------------------------------------------------------------------
-- 9. Interactions – journal des échanges CRM (appels, emails, WhatsApp…)
-- ---------------------------------------------------------------------------
create table if not exists public.interactions (
    id               bigint generated by default as identity primary key,
    created_at       timestamp with time zone not null default now(),
    airtable_id      text unique,
    titre            text,
    date_heure       timestamp with time zone,
    type_interaction text,               -- Appel, Email, WhatsApp, RDV, Autre
    message          text,
    canal            text,
    statut_suivi     text,               -- Traité, En attente, À relancer
    responsable      text,
    contact_id       bigint references public.contacts(id) on delete set null
);

create index if not exists interactions_contact_id_idx on public.interactions(contact_id);

-- ---------------------------------------------------------------------------
-- 10. Newsletter – abonnés à la newsletter AIBS
-- ---------------------------------------------------------------------------
create table if not exists public.newsletter_subscribers (
    id                   bigint generated by default as identity primary key,
    created_at           timestamp with time zone not null default now(),
    airtable_id          text unique,
    email                text not null unique,
    prenom               text,
    date_inscription     date,
    source               text,
    statut               text,               -- Actif, Désabonné
    date_desabonnement   date,
    langue               text                -- Français, Anglais, Autre
);

-- ---------------------------------------------------------------------------
-- 11. Row Level Security – toutes les nouvelles tables
-- ---------------------------------------------------------------------------
alter table public.formations             enable row level security;
alter table public.intervenants           enable row level security;
alter table public.training_sessions      enable row level security;
alter table public.formation_intervenants enable row level security;
alter table public.session_intervenants   enable row level security;
alter table public.inscriptions           enable row level security;
alter table public.paiements              enable row level security;
alter table public.interactions           enable row level security;
alter table public.newsletter_subscribers enable row level security;

-- Formations
create policy "formations_select" on public.formations for select to authenticated using (true);
create policy "formations_insert" on public.formations for insert to authenticated with check (true);
create policy "formations_update" on public.formations for update to authenticated using (true);
create policy "formations_delete" on public.formations for delete to authenticated using (true);

-- Intervenants
create policy "intervenants_select" on public.intervenants for select to authenticated using (true);
create policy "intervenants_insert" on public.intervenants for insert to authenticated with check (true);
create policy "intervenants_update" on public.intervenants for update to authenticated using (true);
create policy "intervenants_delete" on public.intervenants for delete to authenticated using (true);

-- Training Sessions
create policy "training_sessions_select" on public.training_sessions for select to authenticated using (true);
create policy "training_sessions_insert" on public.training_sessions for insert to authenticated with check (true);
create policy "training_sessions_update" on public.training_sessions for update to authenticated using (true);
create policy "training_sessions_delete" on public.training_sessions for delete to authenticated using (true);

-- Junction tables
create policy "formation_intervenants_select" on public.formation_intervenants for select to authenticated using (true);
create policy "formation_intervenants_insert" on public.formation_intervenants for insert to authenticated with check (true);
create policy "formation_intervenants_delete" on public.formation_intervenants for delete to authenticated using (true);

create policy "session_intervenants_select" on public.session_intervenants for select to authenticated using (true);
create policy "session_intervenants_insert" on public.session_intervenants for insert to authenticated with check (true);
create policy "session_intervenants_delete" on public.session_intervenants for delete to authenticated using (true);

-- Inscriptions
create policy "inscriptions_select" on public.inscriptions for select to authenticated using (true);
create policy "inscriptions_insert" on public.inscriptions for insert to authenticated with check (true);
create policy "inscriptions_update" on public.inscriptions for update to authenticated using (true);
create policy "inscriptions_delete" on public.inscriptions for delete to authenticated using (true);

-- Paiements
create policy "paiements_select" on public.paiements for select to authenticated using (true);
create policy "paiements_insert" on public.paiements for insert to authenticated with check (true);
create policy "paiements_update" on public.paiements for update to authenticated using (true);
create policy "paiements_delete" on public.paiements for delete to authenticated using (true);

-- Interactions
create policy "interactions_select" on public.interactions for select to authenticated using (true);
create policy "interactions_insert" on public.interactions for insert to authenticated with check (true);
create policy "interactions_update" on public.interactions for update to authenticated using (true);
create policy "interactions_delete" on public.interactions for delete to authenticated using (true);

-- Newsletter
create policy "newsletter_select" on public.newsletter_subscribers for select to authenticated using (true);
create policy "newsletter_insert" on public.newsletter_subscribers for insert to authenticated with check (true);
create policy "newsletter_update" on public.newsletter_subscribers for update to authenticated using (true);
create policy "newsletter_delete" on public.newsletter_subscribers for delete to authenticated using (true);

-- ---------------------------------------------------------------------------
-- 12. Fonction RPC pour vérifier l'existence d'un email (pour n8n sans auth)
-- Permet au workflow n8n de faire un dédup sans clé service_role
-- ---------------------------------------------------------------------------
create or replace function public.check_contact_email_exists(p_email text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    return exists (
        select 1
        from public.contacts
        where email_jsonb @> jsonb_build_array(jsonb_build_object('email', p_email))
    );
end;
$$;

grant execute on function public.check_contact_email_exists(text) to anon;

-- ---------------------------------------------------------------------------
-- 13. Vue paiements_summary – solde par inscription
-- ---------------------------------------------------------------------------
create or replace view public.inscriptions_summary with (security_invoker = on) as
select
    i.id,
    i.numero_inscription,
    i.date_inscription,
    i.contact_id,
    i.session_id,
    i.statut,
    i.mode_financement,
    i.montant_total,
    i.commentaires,
    i.date_validation,
    co.first_name  || ' ' || co.last_name as contact_nom,
    ts.session_name,
    f.nom          as formation_nom,
    f.slug         as formation_slug,
    coalesce(sum(p.montant) filter (where p.statut_paiement = 'Reçu'), 0) as montant_paye,
    i.montant_total - coalesce(sum(p.montant) filter (where p.statut_paiement = 'Reçu'), 0) as solde_restant,
    count(p.id) as nb_paiements
from public.inscriptions i
    left join public.contacts         co on co.id = i.contact_id
    left join public.training_sessions ts on ts.id = i.session_id
    left join public.formations        f  on f.id  = ts.formation_id
    left join public.paiements         p  on p.inscription_id = i.id
group by i.id, co.first_name, co.last_name, ts.session_name, f.nom, f.slug;
